import { z } from "zod";
import {
  PRESENTATION_SCENE_SCHEMA,
  PRESENTATION_SCENE_VERSION,
  PRESERVATION_ENVELOPE_SCHEMA,
  PRESERVATION_ENVELOPE_VERSION,
  PROJECT_SCHEMA,
  PROJECT_SCHEMA_VERSION,
  type PresentationStudioProject,
} from "../types";
import { defaultProjectDesignSettings } from "./design-standard";

const isoTimestamp = z.string().datetime({ offset: true });
const fontSchema = z.object({
  family: z.string(),
  normalizedFamily: z.string(),
  count: z.number().int().nonnegative(),
  directSlideCount: z.number().int().nonnegative(),
  slideNumbers: z.array(z.number().int().positive()),
  partKinds: z.array(z.string()),
  isThemeFont: z.boolean(),
  isLikelySymbolFont: z.boolean(),
});
const slideSchema = z.object({
  id: z.string(),
  number: z.number().int().positive(),
  sourcePart: z.string().optional(),
  sourcePartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  relationshipPart: z.string().optional(),
  relationshipPartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  title: z.string(),
  text: z.string(),
  textHash: z.string().regex(/^[0-9a-f]{64}$/),
  textRunCount: z.number().int().nonnegative(),
  tableCount: z.number().int().nonnegative(),
  pictureCount: z.number().int().nonnegative(),
  chartCount: z.number().int().nonnegative(),
  connectorCount: z.number().int().nonnegative(),
  commentCount: z.number().int().nonnegative(),
  fonts: z.array(z.string()),
  fontSizes: z.array(z.number().nonnegative()),
  warnings: z.array(z.string()),
});
const tableInventorySchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  ordinal: z.number().int().positive(),
  rowCount: z.number().int().nonnegative(),
  columnCount: z.number().int().nonnegative(),
  mergedCellCount: z.number().int().nonnegative(),
  totalCellCharacterCount: z.number().int().nonnegative().default(0),
  maximumCellCharacterCount: z.number().int().nonnegative().default(0),
  styleId: z.string().optional(),
  styleFlags: z.array(z.string()),
  cellFonts: z.array(z.string()),
  colorTokens: z.array(z.string()),
  marginSignatures: z.array(z.string()),
  styleFingerprint: z.string().regex(/^[0-9a-f]{64}$/),
  contentHash: z.string().regex(/^[0-9a-f]{64}$/).default("0".repeat(64)),
  structureHash: z.string().regex(/^[0-9a-f]{64}$/).default("0".repeat(64)),
});
const pictureInventorySchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  ordinal: z.number().int().positive(),
  name: z.string(),
  description: z.string().optional(),
  relationshipId: z.string().optional(),
  widthEmu: z.number().int().nonnegative().optional(),
  heightEmu: z.number().int().nonnegative().optional(),
  cropped: z.boolean(),
  hasOutline: z.boolean(),
  hasEffect: z.boolean(),
});
const geometrySchema = z.object({ x: z.number().int(), y: z.number().int(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() });
const editableObjectSchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  shapeId: z.string(),
  name: z.string(),
  kind: z.enum(["text", "shape", "picture", "table", "chart", "connector", "group", "graphic-frame"]),
  sourceElement: z.enum(["p:sp", "p:pic", "p:graphicFrame", "p:cxnSp", "p:grpSp"]),
  geometry: geometrySchema.extend({ rotation: z.number() }),
  canMove: z.boolean(),
  canResize: z.boolean(),
  textHash: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  tableId: z.string().optional(),
  pictureId: z.string().optional(),
});
const sceneFidelityStateSchema = z.enum(["editable-native", "preserved-native", "conversion-required", "unsupported-blocking"]);
const sceneFidelityCountsSchema = z.object({
  "editable-native": z.number().int().nonnegative(),
  "preserved-native": z.number().int().nonnegative(),
  "conversion-required": z.number().int().nonnegative(),
  "unsupported-blocking": z.number().int().nonnegative(),
});
const sceneObjectSchema = z.object({
  id: z.string().min(1),
  slideId: z.string().min(1),
  slideNumber: z.number().int().positive(),
  shapeId: z.string().min(1),
  name: z.string(),
  kind: z.enum(["text", "shape", "picture", "table", "chart", "connector", "group", "graphic-frame"]),
  sourceElement: z.enum(["p:sp", "p:pic", "p:graphicFrame", "p:cxnSp", "p:grpSp"]),
  semanticRole: z.enum(["title", "body", "caption", "label", "image", "table", "chart", "connector", "group", "decoration", "other"]),
  fidelityState: sceneFidelityStateSchema,
  fidelityReason: z.string().min(1),
  geometry: geometrySchema.extend({ rotation: z.number() }),
  zIndex: z.number().int().nonnegative(),
  sourceLocator: z.object({
    slidePart: z.string().min(1),
    shapeId: z.string().min(1),
    tableId: z.string().optional(),
    pictureId: z.string().optional(),
  }),
  representation: z.object({
    geometry: z.enum(["native", "partial", "preserved", "none"]),
    text: z.enum(["native", "partial", "preserved", "none"]),
    style: z.enum(["native", "partial", "preserved", "none"]),
    internalStructure: z.enum(["native", "partial", "preserved", "none"]),
  }),
  operations: z.object({
    move: z.boolean(),
    resize: z.boolean(),
    restyle: z.boolean(),
    editText: z.boolean(),
    editTableStyle: z.boolean(),
    replaceMedia: z.boolean(),
    editChartData: z.boolean(),
    editInternalStructure: z.boolean(),
  }),
  contentHash: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  protected: z.boolean(),
});
const sceneSlideSchema = z.object({
  id: z.string().min(1),
  number: z.number().int().positive(),
  sourcePart: z.string().min(1),
  sourcePartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  relationshipPart: z.string().optional(),
  relationshipPartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  sourceTextHash: z.string().regex(/^[0-9a-f]{64}$/),
  targetLayoutId: z.string().optional(),
  objectIds: z.array(z.string().min(1)),
  fidelityCounts: sceneFidelityCountsSchema,
  preservationRequired: z.boolean(),
  protected: z.boolean(),
});
const preservationSlideSchema = z.object({
  slideId: z.string().min(1),
  slideNumber: z.number().int().positive(),
  sourcePart: z.string().min(1),
  sourcePartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  relationshipPart: z.string().optional(),
  relationshipPartSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  sourceTextHash: z.string().regex(/^[0-9a-f]{64}$/),
  objectIds: z.array(z.string().min(1)),
});
const presentationSceneSchema = z.object({
  schema: z.literal(PRESENTATION_SCENE_SCHEMA),
  version: z.literal(PRESENTATION_SCENE_VERSION),
  revision: z.string().min(1),
  sourceSha256: z.string().regex(/^[0-9a-f]{64}$/),
  slideSize: z.object({ width: z.number().int().positive(), height: z.number().int().positive() }),
  templateBinding: z.object({
    sourceClassification: z.enum(["current-ornl", "older-or-modified-ornl", "sponsor", "custom", "mixed", "unknown"]),
    targetTemplateId: z.string().optional(),
    targetDecisionSource: z.enum(["automatic-default", "automatic-source-preservation", "user-selected"]).optional(),
  }),
  slides: z.array(sceneSlideSchema),
  objects: z.array(sceneObjectSchema),
  fidelityCounts: sceneFidelityCountsSchema,
  preservationEnvelope: z.object({
    schema: z.literal(PRESERVATION_ENVELOPE_SCHEMA),
    version: z.literal(PRESERVATION_ENVELOPE_VERSION),
    sourceResourceId: z.string().min(1),
    sourceSha256: z.string().regex(/^[0-9a-f]{64}$/),
    sourceBytesAuthoritative: z.literal(true),
    nativeRenderAuthoritativeForAppearance: z.literal(true),
    exportStrategy: z.literal("surgical-ooxml-overlay"),
    packageFileCount: z.number().int().positive(),
    expandedByteLength: z.number().int().nonnegative(),
    protectedFeatures: z.object({ macros: z.boolean(), oleObjects: z.boolean(), externalRelationships: z.boolean() }),
    blockingFeatures: z.array(z.enum(["macros", "ole-objects", "external-relationships"])),
    slides: z.array(preservationSlideSchema),
  }),
});
const textBoxInventorySchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  ordinal: z.number().int().positive(),
  shapeId: z.string(),
  text: z.string().default(""),
  textHash: z.string().regex(/^[0-9a-f]{64}$/),
  characterCount: z.number().int().nonnegative(),
  paragraphCount: z.number().int().nonnegative(),
  geometry: geometrySchema,
  textInsets: z.object({ left: z.number(), right: z.number(), top: z.number(), bottom: z.number() }).default({ left: 91_440, right: 91_440, top: 45_720, bottom: 45_720 }),
  paragraphLeftMarginsEmu: z.array(z.number()).default([]),
  paragraphIndentsEmu: z.array(z.number()).default([]),
  bulletParagraphCount: z.number().int().nonnegative().default(0),
  opticalLeftOffsetEmu: z.number().default(91_440),
  estimatedOpticalLeftEmu: z.number().default(0),
  opticalAlignmentConfidence: z.enum(["direct", "partial-inheritance"]).default("partial-inheritance"),
  fontFamilies: z.array(z.string()),
  fontSizes: z.array(z.number().nonnegative()),
  directFontSizeKnown: z.boolean(),
  paragraphAlignment: z.enum(["left", "center", "right", "justified", "mixed"]),
  verticalAlignment: z.enum(["top", "middle", "bottom"]),
  role: z.enum(["title", "body", "caption", "label", "other"]),
  autoFit: z.enum(["none", "shrink-text", "resize-shape", "unspecified"]),
  estimatedLineCount: z.number().int().positive(),
  estimatedRequiredHeightEmu: z.number().int().nonnegative(),
  fitRatio: z.number().nonnegative(),
  safeAreaStatus: z.enum(["inside", "near-edge", "off-slide"]),
  warnings: z.array(z.string()),
});
const layoutReviewSchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  shapeId: z.string(),
  rule: z.enum(["overflow-risk", "off-slide", "safe-area", "alignment-ambiguous"]),
  severity: z.enum(["info", "warning", "error"]),
  confidence: z.enum(["high", "medium", "low"]),
  reason: z.string(),
  geometry: geometrySchema,
  fitRatio: z.number().nonnegative().optional(),
});
const alignmentRepairSchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  shapeId: z.string(),
  textHash: z.string().regex(/^[0-9a-f]{64}$/),
  source: z.object({ x: z.number().int(), y: z.number().int(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() }),
  target: z.object({ x: z.number().int(), y: z.number().int(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() }),
  ruleId: z.enum(["cover.dominant-left-edge", "peer.dominant-left-edge"]),
  confidence: z.literal("high"),
  rationale: z.string(),
});
const findingSchema = z.object({
  id: z.string(),
  ruleId: z.string(),
  category: z.enum(["template", "font", "table", "figure", "layout", "production", "technical-review"]),
  severity: z.enum(["info", "warning", "error"]),
  confidence: z.enum(["high", "medium", "low"]),
  slideNumber: z.number().int().positive().optional(),
  message: z.string(),
  evidence: z.string(),
  autoFixable: z.boolean(),
});
const auditSchema = z.object({
  scannedAt: isoTimestamp,
  supportLevel: z.enum(["native-ooxml", "partial", "blocked"]),
  slideCount: z.number().int().nonnegative(),
  masterCount: z.number().int().nonnegative(),
  layoutCount: z.number().int().nonnegative(),
  themeCount: z.number().int().nonnegative(),
  notesCount: z.number().int().nonnegative(),
  legacyCommentCount: z.number().int().nonnegative(),
  modernCommentCount: z.number().int().nonnegative(),
  mediaCount: z.number().int().nonnegative(),
  tableCount: z.number().int().nonnegative(),
  chartCount: z.number().int().nonnegative(),
  pictureCount: z.number().int().nonnegative(),
  containsMacros: z.boolean(),
  containsOleObjects: z.boolean(),
  containsExternalRelationships: z.boolean(),
  packageFileCount: z.number().int().positive(),
  expandedByteLength: z.number().int().nonnegative(),
  slideSize: z.object({ width: z.number().int().positive(), height: z.number().int().positive() }).default({ width: 12_192_000, height: 6_858_000 }),
  classification: z.enum(["current-ornl", "older-or-modified-ornl", "sponsor", "custom", "mixed", "unknown"]),
  classificationEvidence: z.array(z.string()),
  fonts: z.array(fontSchema),
  slides: z.array(slideSchema),
  tables: z.array(tableInventorySchema),
  pictures: z.array(pictureInventorySchema),
  textBoxes: z.array(textBoxInventorySchema).default([]),
  editableObjects: z.array(editableObjectSchema).default([]),
  layoutReviews: z.array(layoutReviewSchema).default([]),
  alignmentRepairs: z.array(alignmentRepairSchema).default([]),
  findings: z.array(findingSchema),
  warnings: z.array(z.string()),
});
const changeSchema = z.object({
  id: z.string(),
  kind: z.enum(["font-family", "table-style", "alignment", "geometry", "layout-remap", "text-style", "decoration"]),
  from: z.string(),
  to: z.string(),
  affectedSlideNumbers: z.array(z.number().int().positive()),
  affectedRunCount: z.number().int().nonnegative(),
  tableIds: z.array(z.string()).optional(),
  profileId: z.string().optional(),
  alignmentRepairs: z.array(alignmentRepairSchema).optional(),
  geometryCommands: z.array(z.object({
    id: z.string(),
    slideNumber: z.number().int().positive(),
    objectId: z.string(),
    shapeId: z.string(),
    sourceElement: z.enum(["p:sp", "p:pic", "p:graphicFrame", "p:cxnSp", "p:grpSp"]),
    objectKind: z.enum(["text", "shape", "picture", "table", "chart", "connector", "group", "graphic-frame"]),
    operation: z.enum(["move", "resize", "move-and-resize"]),
    source: geometrySchema,
    target: geometrySchema,
    rationale: z.string(),
    author: z.enum(["human", "ai"]),
    constraints: z.object({
      allowIntentionalOverlap: z.boolean(),
      allowFitRisk: z.boolean(),
      allowSafeArea: z.boolean(),
      allowAspectRatioChange: z.boolean(),
    }).default({ allowIntentionalOverlap: false, allowFitRisk: false, allowSafeArea: false, allowAspectRatioChange: false }),
    validation: z.object({
      fitRatio: z.number().nonnegative().optional(),
      safeAreaStatus: z.enum(["inside", "near-edge"]),
      overlapObjectIds: z.array(z.string()),
      warnings: z.array(z.string()),
    }).default({ safeAreaStatus: "inside", overlapObjectIds: [], warnings: [] }),
  })).optional(),
  layoutCommands: z.array(z.object({
    id: z.string().min(1),
    slideNumber: z.number().int().positive(),
    templateSha256: z.string().length(64),
    templateLayoutPart: z.string().regex(/^ppt\/slideLayouts\/slideLayout\d+\.xml$/i),
    templateLayoutSha256: z.string().length(64),
    templateLayoutName: z.string().min(1),
    rationale: z.string().min(1).max(1_000),
    author: z.enum(["ai", "human"]),
  })).optional(),
  textStyleCommands: z.array(z.object({
    id: z.string().min(1),
    slideNumber: z.number().int().positive(),
    objectId: z.string().min(1),
    shapeId: z.string().min(1),
    typeface: z.literal("Aptos"),
    fontSizePt: z.number().min(10).max(60).optional(),
    bold: z.boolean().optional(),
    italic: z.boolean().optional(),
    color: z.string().regex(/^#[0-9A-F]{6}$/i).optional(),
    alignment: z.enum(["left", "center", "right"]).optional(),
    verticalAlignment: z.enum(["top", "middle", "bottom"]).optional(),
    insetsInches: z.object({ top: z.number().min(0).max(.25), right: z.number().min(0).max(.25), bottom: z.number().min(0).max(.25), left: z.number().min(0).max(.25) }).optional(),
    rationale: z.string().min(1).max(700),
    author: z.enum(["ai", "human"]),
  })).optional(),
  decorationCommands: z.array(z.object({
    id: z.string().min(1),
    slideNumber: z.number().int().positive(),
    name: z.string().min(1).max(120),
    geometry: geometrySchema,
    fillColor: z.string().regex(/^#[0-9A-F]{6}$/i).optional(),
    lineColor: z.string().regex(/^#[0-9A-F]{6}$/i).optional(),
    lineWidthPt: z.number().min(0).max(6),
    behindContent: z.boolean(),
    rationale: z.string().min(1).max(700),
    author: z.enum(["ai", "human"]),
  })).optional(),
  rationale: z.string(),
  selected: z.boolean(),
});
const proposalSchema = z.object({
  id: z.string(),
  deckId: z.string(),
  baseUpdatedAt: isoTimestamp,
  createdAt: isoTimestamp,
  summary: z.string(),
  status: z.enum(["pending", "applied", "rejected"]),
  mode: z.enum(["font-cleanup", "designer-cleanup", "slide-geometry", "slide-reflow"]).default("font-cleanup"),
  standardVersion: z.string().optional(),
  designDecision: z.object({
    kind: z.literal("semantic-recomposition"),
    workOrderRevision: z.string().min(1),
    targetLayoutId: z.string().min(1),
    targetLayoutName: z.string().min(1),
    targetLayoutSourcePart: z.string().min(1),
    compatibilityScore: z.number().min(0).max(100),
    compatibilityStatus: z.enum(["recommended", "compatible", "poor", "incompatible"]),
    rationale: z.string().min(1).max(1_000),
    bindingCount: z.number().int().positive(),
    application: z.enum(["semantic-zones-on-source-layout", "cloned-native-layout"]),
  }).optional(),
  designReview: z.object({
    decision: z.literal("rejected"),
    actor: z.enum(["ai", "human"]),
    rationale: z.string().min(1).max(1_000),
    reviewedAt: isoTimestamp,
    evidence: z.object({
      slideNumber: z.number().int().positive(),
      renderer: z.literal("powerpoint-native"),
      currentRasterSha256: z.string().length(64),
      proposalRasterSha256: z.string().length(64),
      changedPixelRatio: z.number().min(0).max(1),
    }).optional(),
  }).optional(),
  changes: z.array(changeSchema),
  slideDispositions: z.array(z.object({
    slideNumber: z.number().int().positive(),
    status: z.enum(["change-proposed", "approved-as-is", "needs-review"]),
    reasons: z.array(z.string()),
    changeIds: z.array(z.string()),
  })).default([]),
  slideReviews: z.array(z.object({
    slideNumber: z.number().int().positive(),
    decision: z.enum(["approved", "changes-requested"]),
    reviewedAt: isoTimestamp,
    comment: z.string().min(1).max(4_000).optional(),
  })).default([]),
  tableExceptions: z.array(z.object({
    tableId: z.string(),
    slideNumber: z.number().int().positive(),
    reason: z.string(),
    rule: z.enum(["semantic-color", "complex-structure", "dense-table"]),
  })).default([]),
  layoutExceptions: z.array(layoutReviewSchema).default([]),
});
const deckSchema = z.object({
  id: z.string(),
  name: z.string(),
  sourceResourceId: z.string(),
  sourceSha256: z.string().regex(/^[0-9a-f]{64}$/),
  operationScope: z.enum(["audit-only", "cleanup-only", "reflow", "hybrid", "compose"]),
  templateClassification: z.enum(["current-ornl", "older-or-modified-ornl", "sponsor", "custom", "mixed", "unknown"]),
  targetTemplateId: z.string().optional(),
  targetTemplateConfirmedAt: isoTimestamp.optional(),
  targetTemplateDecisionSource: z.enum(["automatic-default", "automatic-source-preservation", "user-selected"]).optional(),
  designProfile: z.object({
    id: z.string().min(1),
    standardVersion: z.string().min(1),
    templateId: z.string().min(1),
    slideSize: z.literal("16:9"),
    fontFamily: z.literal("Aptos"),
    contentPolicy: z.literal("preserve-exact"),
    adoptedAt: isoTimestamp,
    source: z.enum(["automatic-default", "automatic-source-preservation", "user-selected"]),
    customized: z.boolean(),
  }).optional(),
  status: z.enum(["not-scanned", "audited", "needs-template-decision", "ready-for-cleanup", "proposal-ready", "needs-manual-review", "approved", "exported", "failed"]),
  audit: auditSchema.optional(),
  scene: presentationSceneSchema.optional(),
  proposal: proposalSchema.optional(),
  protectedSlideNumbers: z.array(z.number().int().positive()),
  failureMessage: z.string().max(700).optional(),
  exportedAt: isoTimestamp.optional(),
});

export const projectSchema = z.object({
  schema: z.literal(PROJECT_SCHEMA),
  schemaVersion: z.literal(PROJECT_SCHEMA_VERSION),
  project: z.object({
    id: z.string().min(1),
    name: z.string().min(1).max(240),
    type: z.enum(["review-batch", "single-deck", "new-presentation"]),
    createdAt: isoTimestamp,
    updatedAt: isoTimestamp,
  }),
  settings: z.object({
    contentPolicy: z.enum(["preserve-exact", "source-grounded-generative"]),
    defaultOperationScope: z.enum(["audit-only", "cleanup-only", "reflow", "hybrid", "compose"]),
    autosave: z.boolean(),
    designStandardVersion: z.string().min(1).default(defaultProjectDesignSettings().designStandardVersion),
    defaultProfileId: z.string().min(1).default(defaultProjectDesignSettings().defaultProfileId),
    defaultSlideSize: z.literal("16:9").default("16:9"),
    defaultFontFamily: z.literal("Aptos").default("Aptos"),
  }),
  resources: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    mediaType: z.string().min(1),
    byteLength: z.number().int().nonnegative(),
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
    roles: z.array(z.enum(["import-origin", "prior-approved-revision", "style-exemplar", "grounding-source", "slide-media", "chart-data", "template-source", "reference-only"])).min(1),
    kind: z.enum(["presentation", "document", "data", "image", "audio", "video", "other"]).optional(),
    support: z.array(z.enum(["source-readable", "previewable", "placeable", "pptx-preserved", "unsupported"])).optional(),
    processing: z.object({
      status: z.enum(["indexed", "stored-only", "needs-review"]),
      summary: z.string().max(1_000),
      processedAt: isoTimestamp,
      warnings: z.array(z.string().max(1_000)).max(50),
    }).optional(),
    derivatives: z.array(z.object({
      id: z.string().min(1),
      kind: z.literal("extracted-text"),
      mediaType: z.literal("text/plain"),
      byteLength: z.number().int().nonnegative(),
      sha256: z.string().regex(/^[0-9a-f]{64}$/),
      createdAt: isoTimestamp,
      processor: z.string().min(1).max(240),
      truncated: z.boolean(),
      bytes: z.instanceof(Uint8Array).optional(),
    })).max(20).optional(),
    createdAt: isoTimestamp,
    sourcePath: z.string().optional(),
    embedded: z.literal(true),
    bytes: z.instanceof(Uint8Array).optional(),
    mcpAccess: z.enum(["none", "metadata", "text", "preview"]),
  })),
  styleExemplars: z.array(z.object({
    id: z.string(),
    name: z.string(),
    kind: z.enum(["table", "figure"]),
    resourceId: z.string(),
    deckId: z.string(),
    slideNumber: z.number().int().positive(),
    objectOrdinal: z.number().int().positive(),
    scope: z.enum(["deck", "batch"]),
    createdAt: isoTimestamp,
  })),
  designThreads: z.array(z.object({
    id: z.string().min(1),
    deckId: z.string().min(1),
    slideId: z.string().min(1),
    slideNumber: z.number().int().positive(),
    baseRevision: isoTimestamp,
    anchor: z.object({
      kind: z.literal("region"),
      x: z.number().min(0).max(1),
      y: z.number().min(0).max(1),
      width: z.number().positive().max(1),
      height: z.number().positive().max(1),
    }),
    comment: z.string().min(1).max(4_000),
    status: z.enum(["note", "submitted", "proposal-ready", "resolved", "needs-reanchor"]),
    createdAt: isoTimestamp,
    updatedAt: isoTimestamp,
    submittedAt: isoTimestamp.optional(),
  })).default([]),
  decks: z.array(deckSchema),
  activity: z.array(z.object({ id: z.string(), at: isoTimestamp, action: z.string(), detail: z.string() })),
});

export function createProject(name = "Untitled review batch"): PresentationStudioProject {
  const now = new Date().toISOString();
  return {
    schema: PROJECT_SCHEMA,
    schemaVersion: PROJECT_SCHEMA_VERSION,
    project: {
      id: crypto.randomUUID(),
      name,
      type: "review-batch",
      createdAt: now,
      updatedAt: now,
    },
    settings: {
      contentPolicy: "preserve-exact",
      defaultOperationScope: "cleanup-only",
      autosave: true,
      ...defaultProjectDesignSettings(),
    },
    resources: [],
    styleExemplars: [],
    designThreads: [],
    decks: [],
    activity: [{ id: crypto.randomUUID(), at: now, action: "project-created", detail: "Created a conservative cleanup review batch." }],
  };
}

export function touchProject(project: PresentationStudioProject, action: string, detail: string): PresentationStudioProject {
  const now = new Date().toISOString();
  return {
    ...project,
    project: { ...project.project, updatedAt: now },
    activity: [...project.activity, { id: crypto.randomUUID(), at: now, action, detail }],
  };
}

export function projectForJson(project: PresentationStudioProject) {
  return {
    ...project,
    resources: project.resources.map(({ bytes: _bytes, sourcePath: _sourcePath, derivatives, ...resource }) => ({
      ...resource,
      mcpAccess: "none" as const,
      derivatives: derivatives?.map(({ bytes: _derivativeBytes, ...derivative }) => derivative),
    })),
  };
}
