import { z } from "zod";
import { PROJECT_SCHEMA, PROJECT_SCHEMA_VERSION, type PresentationStudioProject } from "../types";
import { defaultProjectDesignSettings } from "./design-standard";

const isoTimestamp = z.string().datetime({ offset: true });
const fontSchema = z.object({
  family: z.string(),
  normalizedFamily: z.string(),
  count: z.number().int().nonnegative(),
  directSlideCount: z.number().int().nonnegative(),
  slideNumbers: z.array(z.number().int().positive()),
  partKinds: z.array(z.string()),
  isThemeFont: z.boolean(),
  isLikelySymbolFont: z.boolean(),
});
const slideSchema = z.object({
  id: z.string(),
  number: z.number().int().positive(),
  title: z.string(),
  text: z.string(),
  textHash: z.string().regex(/^[0-9a-f]{64}$/),
  textRunCount: z.number().int().nonnegative(),
  tableCount: z.number().int().nonnegative(),
  pictureCount: z.number().int().nonnegative(),
  chartCount: z.number().int().nonnegative(),
  connectorCount: z.number().int().nonnegative(),
  commentCount: z.number().int().nonnegative(),
  fonts: z.array(z.string()),
  fontSizes: z.array(z.number().nonnegative()),
  warnings: z.array(z.string()),
});
const tableInventorySchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  ordinal: z.number().int().positive(),
  rowCount: z.number().int().nonnegative(),
  columnCount: z.number().int().nonnegative(),
  mergedCellCount: z.number().int().nonnegative(),
  totalCellCharacterCount: z.number().int().nonnegative().default(0),
  maximumCellCharacterCount: z.number().int().nonnegative().default(0),
  styleId: z.string().optional(),
  styleFlags: z.array(z.string()),
  cellFonts: z.array(z.string()),
  colorTokens: z.array(z.string()),
  marginSignatures: z.array(z.string()),
  styleFingerprint: z.string().regex(/^[0-9a-f]{64}$/),
  contentHash: z.string().regex(/^[0-9a-f]{64}$/).default("0".repeat(64)),
  structureHash: z.string().regex(/^[0-9a-f]{64}$/).default("0".repeat(64)),
});
const pictureInventorySchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  ordinal: z.number().int().positive(),
  name: z.string(),
  description: z.string().optional(),
  relationshipId: z.string().optional(),
  widthEmu: z.number().int().nonnegative().optional(),
  heightEmu: z.number().int().nonnegative().optional(),
  cropped: z.boolean(),
  hasOutline: z.boolean(),
  hasEffect: z.boolean(),
});
const alignmentRepairSchema = z.object({
  id: z.string(),
  slideNumber: z.number().int().positive(),
  shapeId: z.string(),
  textHash: z.string().regex(/^[0-9a-f]{64}$/),
  source: z.object({ x: z.number().int(), y: z.number().int(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() }),
  target: z.object({ x: z.number().int(), y: z.number().int(), width: z.number().int().nonnegative(), height: z.number().int().nonnegative() }),
  ruleId: z.literal("cover.dominant-left-edge"),
  confidence: z.literal("high"),
  rationale: z.string(),
});
const findingSchema = z.object({
  id: z.string(),
  ruleId: z.string(),
  category: z.enum(["template", "font", "table", "figure", "layout", "production", "technical-review"]),
  severity: z.enum(["info", "warning", "error"]),
  confidence: z.enum(["high", "medium", "low"]),
  slideNumber: z.number().int().positive().optional(),
  message: z.string(),
  evidence: z.string(),
  autoFixable: z.boolean(),
});
const auditSchema = z.object({
  scannedAt: isoTimestamp,
  supportLevel: z.enum(["native-ooxml", "partial", "blocked"]),
  slideCount: z.number().int().nonnegative(),
  masterCount: z.number().int().nonnegative(),
  layoutCount: z.number().int().nonnegative(),
  themeCount: z.number().int().nonnegative(),
  notesCount: z.number().int().nonnegative(),
  legacyCommentCount: z.number().int().nonnegative(),
  modernCommentCount: z.number().int().nonnegative(),
  mediaCount: z.number().int().nonnegative(),
  tableCount: z.number().int().nonnegative(),
  chartCount: z.number().int().nonnegative(),
  pictureCount: z.number().int().nonnegative(),
  containsMacros: z.boolean(),
  containsOleObjects: z.boolean(),
  containsExternalRelationships: z.boolean(),
  packageFileCount: z.number().int().positive(),
  expandedByteLength: z.number().int().nonnegative(),
  classification: z.enum(["current-ornl", "older-or-modified-ornl", "sponsor", "custom", "mixed", "unknown"]),
  classificationEvidence: z.array(z.string()),
  fonts: z.array(fontSchema),
  slides: z.array(slideSchema),
  tables: z.array(tableInventorySchema),
  pictures: z.array(pictureInventorySchema),
  alignmentRepairs: z.array(alignmentRepairSchema).default([]),
  findings: z.array(findingSchema),
  warnings: z.array(z.string()),
});
const changeSchema = z.object({
  id: z.string(),
  kind: z.enum(["font-family", "table-style", "alignment"]),
  from: z.string(),
  to: z.string(),
  affectedSlideNumbers: z.array(z.number().int().positive()),
  affectedRunCount: z.number().int().nonnegative(),
  tableIds: z.array(z.string()).optional(),
  profileId: z.string().optional(),
  alignmentRepairs: z.array(alignmentRepairSchema).optional(),
  rationale: z.string(),
  selected: z.boolean(),
});
const proposalSchema = z.object({
  id: z.string(),
  deckId: z.string(),
  baseUpdatedAt: isoTimestamp,
  createdAt: isoTimestamp,
  summary: z.string(),
  status: z.enum(["pending", "applied", "rejected"]),
  mode: z.enum(["font-cleanup", "designer-cleanup"]).default("font-cleanup"),
  standardVersion: z.string().optional(),
  changes: z.array(changeSchema),
  slideDispositions: z.array(z.object({
    slideNumber: z.number().int().positive(),
    status: z.enum(["change-proposed", "approved-as-is", "needs-review"]),
    reasons: z.array(z.string()),
    changeIds: z.array(z.string()),
  })).default([]),
  tableExceptions: z.array(z.object({
    tableId: z.string(),
    slideNumber: z.number().int().positive(),
    reason: z.string(),
    rule: z.enum(["semantic-color", "complex-structure", "dense-table"]),
  })).default([]),
});
const deckSchema = z.object({
  id: z.string(),
  name: z.string(),
  sourceResourceId: z.string(),
  sourceSha256: z.string().regex(/^[0-9a-f]{64}$/),
  operationScope: z.enum(["audit-only", "cleanup-only", "reflow", "hybrid", "compose"]),
  templateClassification: z.enum(["current-ornl", "older-or-modified-ornl", "sponsor", "custom", "mixed", "unknown"]),
  targetTemplateId: z.string().optional(),
  targetTemplateConfirmedAt: isoTimestamp.optional(),
  targetTemplateDecisionSource: z.enum(["automatic-default", "automatic-source-preservation", "user-selected"]).optional(),
  designProfile: z.object({
    id: z.string().min(1),
    standardVersion: z.string().min(1),
    templateId: z.string().min(1),
    slideSize: z.literal("16:9"),
    fontFamily: z.literal("Aptos"),
    contentPolicy: z.literal("preserve-exact"),
    adoptedAt: isoTimestamp,
    source: z.enum(["automatic-default", "automatic-source-preservation", "user-selected"]),
    customized: z.boolean(),
  }).optional(),
  status: z.enum(["not-scanned", "audited", "needs-template-decision", "ready-for-cleanup", "proposal-ready", "needs-manual-review", "approved", "exported", "failed"]),
  audit: auditSchema.optional(),
  proposal: proposalSchema.optional(),
  protectedSlideNumbers: z.array(z.number().int().positive()),
  failureMessage: z.string().max(700).optional(),
  exportedAt: isoTimestamp.optional(),
});

export const projectSchema = z.object({
  schema: z.literal(PROJECT_SCHEMA),
  schemaVersion: z.literal(PROJECT_SCHEMA_VERSION),
  project: z.object({
    id: z.string().min(1),
    name: z.string().min(1).max(240),
    type: z.enum(["review-batch", "single-deck", "new-presentation"]),
    createdAt: isoTimestamp,
    updatedAt: isoTimestamp,
  }),
  settings: z.object({
    contentPolicy: z.enum(["preserve-exact", "source-grounded-generative"]),
    defaultOperationScope: z.enum(["audit-only", "cleanup-only", "reflow", "hybrid", "compose"]),
    autosave: z.boolean(),
    designStandardVersion: z.string().min(1).default(defaultProjectDesignSettings().designStandardVersion),
    defaultProfileId: z.string().min(1).default(defaultProjectDesignSettings().defaultProfileId),
    defaultSlideSize: z.literal("16:9").default("16:9"),
    defaultFontFamily: z.literal("Aptos").default("Aptos"),
  }),
  resources: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    mediaType: z.string().min(1),
    byteLength: z.number().int().nonnegative(),
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
    roles: z.array(z.enum(["import-origin", "prior-approved-revision", "style-exemplar", "grounding-source", "slide-media", "chart-data", "template-source", "reference-only"])).min(1),
    kind: z.enum(["presentation", "document", "data", "image", "audio", "video", "other"]).optional(),
    support: z.array(z.enum(["source-readable", "previewable", "placeable", "pptx-preserved", "unsupported"])).optional(),
    processing: z.object({
      status: z.enum(["indexed", "stored-only", "needs-review"]),
      summary: z.string().max(1_000),
      processedAt: isoTimestamp,
      warnings: z.array(z.string().max(1_000)).max(50),
    }).optional(),
    derivatives: z.array(z.object({
      id: z.string().min(1),
      kind: z.literal("extracted-text"),
      mediaType: z.literal("text/plain"),
      byteLength: z.number().int().nonnegative(),
      sha256: z.string().regex(/^[0-9a-f]{64}$/),
      createdAt: isoTimestamp,
      processor: z.string().min(1).max(240),
      truncated: z.boolean(),
      bytes: z.instanceof(Uint8Array).optional(),
    })).max(20).optional(),
    createdAt: isoTimestamp,
    sourcePath: z.string().optional(),
    embedded: z.literal(true),
    bytes: z.instanceof(Uint8Array).optional(),
    mcpAccess: z.enum(["none", "metadata", "text", "preview"]),
  })),
  styleExemplars: z.array(z.object({
    id: z.string(),
    name: z.string(),
    kind: z.enum(["table", "figure"]),
    resourceId: z.string(),
    deckId: z.string(),
    slideNumber: z.number().int().positive(),
    objectOrdinal: z.number().int().positive(),
    scope: z.enum(["deck", "batch"]),
    createdAt: isoTimestamp,
  })),
  designThreads: z.array(z.object({
    id: z.string().min(1),
    deckId: z.string().min(1),
    slideId: z.string().min(1),
    slideNumber: z.number().int().positive(),
    baseRevision: isoTimestamp,
    anchor: z.object({
      kind: z.literal("region"),
      x: z.number().min(0).max(1),
      y: z.number().min(0).max(1),
      width: z.number().positive().max(1),
      height: z.number().positive().max(1),
    }),
    comment: z.string().min(1).max(4_000),
    status: z.enum(["note", "submitted", "proposal-ready", "resolved", "needs-reanchor"]),
    createdAt: isoTimestamp,
    updatedAt: isoTimestamp,
    submittedAt: isoTimestamp.optional(),
  })).default([]),
  decks: z.array(deckSchema),
  activity: z.array(z.object({ id: z.string(), at: isoTimestamp, action: z.string(), detail: z.string() })),
});

export function createProject(name = "Untitled review batch"): PresentationStudioProject {
  const now = new Date().toISOString();
  return {
    schema: PROJECT_SCHEMA,
    schemaVersion: PROJECT_SCHEMA_VERSION,
    project: {
      id: crypto.randomUUID(),
      name,
      type: "review-batch",
      createdAt: now,
      updatedAt: now,
    },
    settings: {
      contentPolicy: "preserve-exact",
      defaultOperationScope: "cleanup-only",
      autosave: true,
      ...defaultProjectDesignSettings(),
    },
    resources: [],
    styleExemplars: [],
    designThreads: [],
    decks: [],
    activity: [{ id: crypto.randomUUID(), at: now, action: "project-created", detail: "Created a conservative cleanup review batch." }],
  };
}

export function touchProject(project: PresentationStudioProject, action: string, detail: string): PresentationStudioProject {
  const now = new Date().toISOString();
  return {
    ...project,
    project: { ...project.project, updatedAt: now },
    activity: [...project.activity, { id: crypto.randomUUID(), at: now, action, detail }],
  };
}

export function projectForJson(project: PresentationStudioProject) {
  return {
    ...project,
    resources: project.resources.map(({ bytes: _bytes, sourcePath: _sourcePath, derivatives, ...resource }) => ({
      ...resource,
      mcpAccess: "none" as const,
      derivatives: derivatives?.map(({ bytes: _derivativeBytes, ...derivative }) => derivative),
    })),
  };
}
