import assert from "node:assert/strict";
import test from "node:test";
import packagedStandard from "../shared/presentation-design-standard.json";
import { PRESENTATION_DESIGN_STANDARD } from "../src/lib/design-standard";
import { createProject, projectSchema } from "../src/lib/project";

test("one versioned design standard drives project defaults and MCP", () => {
  const project = createProject("Design standard test");
  assert.equal(PRESENTATION_DESIGN_STANDARD.version, packagedStandard.version);
  assert.equal(project.settings.designStandardVersion, packagedStandard.version);
  assert.equal(project.settings.defaultSlideSize, "16:9");
  assert.equal(project.settings.defaultFontFamily, "Aptos");
  assert.equal(packagedStandard.tableProfile.fontFamily, "Aptos");
  assert.equal(packagedStandard.tableProfile.cellPaddingPt.left, 6);
  assert.equal(packagedStandard.tableProfile.strokes.outer, "none");
  assert.equal(packagedStandard.semanticVisualPolicy.tableColorPolicy, "preserve-source");
  assert.equal(packagedStandard.semanticVisualPolicy.tableColorRoles.accent6.tint100, "#FBC9DF");
  assert.match(packagedStandard.autonomy.approvalPolicy, /routine deterministic design choices/i);
  assert.match(packagedStandard.componentSystem.patterns.technicalFigure, /preserve.*source-locked evidence unit/i);
  assert.match(packagedStandard.studioWebDesign.requiredLoop.join(" "), /Found issues.*Fixing.*Rechecking original intent/i);
  assert.match(packagedStandard.studioWebDesign.antiPatterns.join(" "), /Blindly redrawing screenshots, code, technical diagrams/i);
  assert.match(packagedStandard.studioWebDesign.nativeTemplateBase, /PowerPoint-native layout render/i);
  assert.match(packagedStandard.studioWebDesign.constraintOperations.align, /rendered text starts/i);
  assert.match(packagedStandard.studioWebDesign.figureModel.redrawGate, /verified information and relationships/i);
  assert.match(packagedStandard.studioWebDesign.designMemory, /recorded ready/i);
  assert.deepEqual(Object.keys(packagedStandard.interventionPolicy.levels), ["preserve", "polish", "recompose", "rebuild-figure"]);
  assert.match(packagedStandard.interventionPolicy.sourceWinsGate.join(" "), /source strengths.*candidate improvements.*source\/candidate\/equivalent preference/i);
  assert.ok(packagedStandard.studioWebDesign.communicationArchetypes.supported.includes("technical-diagram"));
  assert.match(packagedStandard.studioWebDesign.communicationArchetypes.principle, /communication job before choosing coordinates/i);
  assert.match(packagedStandard.studioWebDesign.communicationArchetypes.selectionSequence.join(" "), /exact layout only when every required content and relationship group.*responsive shared Studio recipe/i);
  assert.match(packagedStandard.studioWebDesign.templateLayoutContracts.nativeAuthority, /master.*custom layout.*footer/i);
  assert.match(packagedStandard.studioWebDesign.templateLayoutContracts.selectionPolicies.sacred, /protected compositions/i);
  assert.match(packagedStandard.componentSystem.layoutRecipes["title-challenges-evidence"].regions, /three equal.*evidence/i);
  assert.match(packagedStandard.componentSystem.layoutRecipes["title-process-flow"].regions, /source relationship and z-order/i);
  assert.match(packagedStandard.componentSystem.layoutRecipes["title-question-diagram"].regions, /source-locked technical evidence unit/i);
  assert.match(packagedStandard.componentSystem.layoutRecipes["title-image-series"].regions, /image.*heading.*body/i);
  assert.match(packagedStandard.componentSystem.components.equalEvidenceField, /differing aspect ratios.*without distortion/i);
  assert.ok(packagedStandard.studioWebDesign.supportedRecipes.includes("ornl-title-question-diagram"));
  assert.ok(packagedStandard.studioWebDesign.supportedRecipes.includes("ornl-title-image-series"));
  assert.match(packagedStandard.everySlideChecklist.join(" "), /Peer image-heading-evidence groups.*semantic series/i);
  assert.match(packagedStandard.visualQaLoop.join(" "), /successful compile as a candidate.*faithful source pixels/i);
  assert.match(packagedStandard.tableRules.join(" "), /PowerPoint-native cell clearance/i);
  assert.match(packagedStandard.tableRules.join(" "), /column-width and row-height proportions.*relational geometry/i);
  assert.match(packagedStandard.studioWebDesign.communicationArchetypes.qualification, /representative.*every communication archetype/i);
  assert.match(packagedStandard.studioWebDesign.conceptReference.role, /art direction/i);
  assert.match(packagedStandard.studioWebDesign.conceptReference.reconstruction, /Do not auto-trace/i);
  assert.equal(packagedStandard.studioWebDesign.visualNeedWorkflow.defaultDisclosure, "abstract-structure-only");
  assert.match(packagedStandard.studioWebDesign.visualNeedWorkflow.executionContract, /exactly one raster.*ONLY ALLOWED TEXT.*LOGO.*OMIT/i);
  assert.match(packagedStandard.studioWebDesign.visualNeedWorkflow.brandExpressionPass, /affirmative.*restrained.*balanced.*expressive/i);
  assert.match(packagedStandard.studioWebDesign.visualNeedWorkflow.reconstruction, /reconstruct_studio_concept.*typography-only/i);
  assert.match(packagedStandard.ornlRules.join(" "), /Do not equate ORNL branding.*green and navy panels/i);
  assert.match(packagedStandard.studioWebDesign.requiredLoop.join(" "), /at most three passes/i);
  assert.match(packagedStandard.precisionLayout.deckQualification.reviewProtocol.join(" "), /contact sheet.*clean full-size source and candidate.*raster hashes/i);
  assert.match(packagedStandard.precisionLayout.deckQualification.automationBoundary, /Portable CI.*self-hosted.*client decks and renders are never uploaded/i);
  assert.deepEqual(packagedStandard.precisionLayout.deckQualification.reviewStates, ["visual-review-required", "review-complete", "revision-required", "held"]);
  assert.match(packagedStandard.studioWebDesign.requiredLoop.join(" "), /do not qualify unchanged bytes.*three automatic attempts/i);
  assert.match(packagedStandard.ornlRules.join(" "), /existing populated ORNL title slide as sacred.*Do not recompose, restyle, move, resize, add to, remove from, or replace it/i);
});

test("older project metadata adopts design defaults without inventing review threads", () => {
  const legacy = createProject("Legacy test") as unknown as Record<string, unknown>;
  const settings = { ...(legacy.settings as Record<string, unknown>) };
  delete settings.designStandardVersion;
  delete settings.defaultProfileId;
  delete settings.defaultSlideSize;
  delete settings.defaultFontFamily;
  legacy.settings = settings;
  delete legacy.designThreads;
  const parsed = projectSchema.parse(legacy);
  assert.equal(parsed.settings.defaultSlideSize, "16:9");
  assert.equal(parsed.settings.defaultFontFamily, "Aptos");
  assert.deepEqual(parsed.designThreads, []);
});
