import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

test("standard STDIO MCP server advertises bounded audit, Resource, and proposal tools", async () => {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.join(root, "mcp", "server.mjs")] });
  const client = new Client({ name: "presentation-studio-test", version: "0.1.0" });
  try {
    await client.connect(transport);
    const result = await client.listTools();
    assert.deepEqual(result.tools.map((tool) => tool.name).sort(), ["get_app_status", "get_cleanup_rule_profile", "get_deck_audit", "get_deck_design_work_order", "get_deck_scene_summary", "get_design_contract", "get_design_thread", "get_pending_proposal_manifest", "get_slide_design_context", "get_slide_design_work_order", "get_slide_render", "get_slide_render_comparison", "get_slide_scene", "get_template_layout_catalog", "get_template_layout_render", "list_decks", "list_design_threads", "list_resources", "recommend_slide_layouts", "reject_design_proposal", "stage_designer_cleanup", "stage_font_cleanup", "stage_slide_geometry_update", "stage_slide_layout_update", "stage_slide_native_layout", "stage_slide_recomposition", "stage_slide_visual_design", "stage_table_design_update"]);
    const contractTool = result.tools.find((tool) => tool.name === "get_design_contract");
    assert.match(contractTool?.description ?? "", /improving every slide/i);
    const contract = await client.callTool({ name: "get_design_contract", arguments: {} });
    assert.equal(contract.isError, undefined);
    assert.equal((contract.structuredContent as { defaultMode?: { name?: string } })?.defaultMode?.name, "designer-cleanup");
    assert.match(JSON.stringify(contract.structuredContent), /independently rendered export/i);
    assert.match(JSON.stringify(contract.structuredContent), /design thread/i);
    assert.match(JSON.stringify(contract.structuredContent), /stable object, text range, table cell\/range, or normalized region/i);
    assert.match(JSON.stringify(contract.structuredContent), /measure every cell/i);
    assert.match(JSON.stringify(contract.structuredContent), /continuation slide/i);
    assert.match(JSON.stringify(contract.structuredContent), /reversible transaction history/i);
    assert.equal((contract.structuredContent as { defaults?: { slide?: { aspectRatio?: string }; typography?: { family?: string } } })?.defaults?.slide?.aspectRatio, "16:9");
    assert.equal((contract.structuredContent as { defaults?: { typography?: { family?: string } } })?.defaults?.typography?.family, "Aptos");
    assert.equal((contract.structuredContent as { tableProfile?: { cellPaddingPt?: { left?: number } } })?.tableProfile?.cellPaddingPt?.left, 6);
    assert.match(JSON.stringify(contract.structuredContent), /Do not redraw each slide as an unrelated one-off canvas/i);
    const stageTool = result.tools.find((tool) => tool.name === "stage_font_cleanup");
    assert.equal(stageTool?.annotations?.destructiveHint, false);
    assert.equal(stageTool?.annotations?.readOnlyHint, false);
    const designerTool = result.tools.find((tool) => tool.name === "stage_designer_cleanup");
    assert.match(designerTool?.description ?? "", /every slide/i);
    assert.match(designerTool?.description ?? "", /semantic colors/i);
    assert.match(designerTool?.description ?? "", /text-box alignment/i);
    assert.equal(designerTool?.annotations?.destructiveHint, false);
    const geometryTool = result.tools.find((tool) => tool.name === "stage_slide_geometry_update");
    assert.match(geometryTool?.description ?? "", /stable editable object/i);
    assert.match(geometryTool?.description ?? "", /Current\/Proposal/i);
    assert.equal(geometryTool?.annotations?.destructiveHint, false);
    const layoutTool = result.tools.find((tool) => tool.name === "stage_slide_layout_update");
    assert.match(layoutTool?.description ?? "", /one atomic design transaction/i);
    assert.match(layoutTool?.description ?? "", /worsened text fit/i);
    assert.match(layoutTool?.description ?? "", /newly increased overlap/i);
    assert.equal(layoutTool?.annotations?.destructiveHint, false);
    const visualDesignTool = result.tools.find((tool) => tool.name === "stage_slide_visual_design");
    assert.match(visualDesignTool?.description ?? "", /editable PowerPoint-native text hierarchy/i);
    assert.match(visualDesignTool?.description ?? "", /cannot add or rewrite claims/i);
    assert.match(visualDesignTool?.description ?? "", /accumulate/i);
    assert.equal(visualDesignTool?.annotations?.destructiveHint, false);
    const tableDesignTool = result.tools.find((tool) => tool.name === "stage_table_design_update");
    assert.match(tableDesignTool?.description ?? "", /dense-technical/i);
    assert.match(tableDesignTool?.description ?? "", /shared/i);
    assert.match(tableDesignTool?.description ?? "", /unrelated comments remain active/i);
    assert.match(JSON.stringify(tableDesignTool?.inputSchema), /addressedThreadIds/);
    const proposalManifestTool = result.tools.find((tool) => tool.name === "get_pending_proposal_manifest");
    assert.match(proposalManifestTool?.description ?? "", /selected command kinds/i);
    assert.match(proposalManifestTool?.description ?? "", /without returning slide text or presentation bytes/i);
    assert.equal(proposalManifestTool?.annotations?.readOnlyHint, true);
    const renderTool = result.tools.find((tool) => tool.name === "get_slide_render");
    assert.match(renderTool?.description ?? "", /Microsoft PowerPoint render/i);
    assert.match(renderTool?.description ?? "", /renderer provenance/i);
    assert.match(JSON.stringify(renderTool?.inputSchema), /source/);
    assert.match(JSON.stringify(renderTool?.inputSchema), /export/);
    const catalogTool = result.tools.find((tool) => tool.name === "get_template_layout_catalog");
    assert.match(catalogTool?.description ?? "", /semantic intent/i);
    assert.match(catalogTool?.description ?? "", /no template bytes/i);
    assert.equal(catalogTool?.annotations?.readOnlyHint, true);
    const layoutRenderTool = result.tools.find((tool) => tool.name === "get_template_layout_render");
    assert.match(layoutRenderTool?.description ?? "", /authoritative Microsoft PowerPoint render/i);
    assert.match(layoutRenderTool?.description ?? "", /slot geometry/i);
    assert.equal(layoutRenderTool?.annotations?.readOnlyHint, true);
    const recommendationTool = result.tools.find((tool) => tool.name === "recommend_slide_layouts");
    assert.match(recommendationTool?.description ?? "", /deterministically rank/i);
    assert.match(recommendationTool?.description ?? "", /PowerPoint-native renders/i);
    assert.equal(recommendationTool?.annotations?.readOnlyHint, true);
    const sceneSummaryTool = result.tools.find((tool) => tool.name === "get_deck_scene_summary");
    assert.match(sceneSummaryTool?.description ?? "", /editable-native/i);
    assert.match(sceneSummaryTool?.description ?? "", /package bytes/i);
    assert.equal(sceneSummaryTool?.annotations?.readOnlyHint, true);
    const slideSceneTool = result.tools.find((tool) => tool.name === "get_slide_scene");
    assert.match(slideSceneTool?.description ?? "", /source-bound object/i);
    assert.match(slideSceneTool?.description ?? "", /z-order/i);
    assert.match(slideSceneTool?.description ?? "", /authoritative Current render/i);
    assert.equal(slideSceneTool?.annotations?.readOnlyHint, true);
    const workOrderTool = result.tools.find((tool) => tool.name === "get_slide_design_work_order");
    assert.match(workOrderTool?.description ?? "", /exact locked copy/i);
    assert.match(workOrderTool?.description ?? "", /iterative visual-design loop/i);
    assert.equal(workOrderTool?.annotations?.readOnlyHint, true);
    const deckWorkOrderTool = result.tools.find((tool) => tool.name === "get_deck_design_work_order");
    assert.match(deckWorkOrderTool?.description ?? "", /cover, text-led content, diagram, image-heavy, and dense table/i);
    const comparisonTool = result.tools.find((tool) => tool.name === "get_slide_render_comparison");
    assert.match(comparisonTool?.description ?? "", /side-by-side Microsoft PowerPoint image/i);
    assert.match(comparisonTool?.description ?? "", /does not prove the proposal is better/i);
    const rejectTool = result.tools.find((tool) => tool.name === "reject_design_proposal");
    assert.match(rejectTool?.description ?? "", /visual-regression rationale/i);
    assert.match(rejectTool?.description ?? "", /never apply or export/i);
    assert.equal(rejectTool?.annotations?.destructiveHint, false);
    const recomposeTool = result.tools.find((tool) => tool.name === "stage_slide_recomposition");
    assert.match(recomposeTool?.description ?? "", /semantic slots/i);
    assert.match(recomposeTool?.description ?? "", /Atomically apply one real approved Template Pack layout/i);
    assert.match(recomposeTool?.description ?? "", /reuses an exact SHA-256-matching native layout/i);
    assert.equal(recomposeTool?.annotations?.destructiveHint, false);
    const nativeLayoutTool = result.tools.find((tool) => tool.name === "stage_slide_native_layout");
    assert.match(nativeLayoutTool?.description ?? "", /reuses an exact SHA-256-matching native layout/i);
    assert.match(nativeLayoutTool?.description ?? "", /master\/layout\/theme\/media dependency graph/i);
    assert.match(nativeLayoutTool?.description ?? "", /placeholder identities/i);
    assert.match(nativeLayoutTool?.description ?? "", /repoints only the named slide/i);
    assert.match(nativeLayoutTool?.description ?? "", /reflow scope/i);
    assert.equal(nativeLayoutTool?.annotations?.destructiveHint, false);
  } finally {
    await client.close();
  }
});
