import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { stripImagePayloads } from "../mcp/image-payload.mjs";

test("MCP image metadata never duplicates encoded or raw raster payloads", () => {
  const metadata = stripImagePayloads([{ id: "contact-sheet", mimeType: "image/png", width: 1200, data: "encoded", bytes: new Uint8Array([1, 2, 3]) }]);
  assert.deepEqual(metadata, [{ id: "contact-sheet", mimeType: "image/png", width: 1200 }]);
  assert.doesNotMatch(JSON.stringify(metadata), /encoded|\"bytes\"/);
});

test("standard STDIO MCP server advertises bounded audit, Resource, and proposal tools", async () => {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.join(root, "mcp", "server.mjs")] });
  const client = new Client({ name: "presentation-studio-test", version: "0.2.0" });
  try {
    await client.connect(transport);
    const result = await client.listTools();
    assert.deepEqual(result.tools.map((tool) => tool.name).sort(), ["attach_studio_concept_reference", "author_studio_connector", "build_studio_presentation", "cancel_studio_presentation_build", "clear_studio_table_continuation", "create_studio_presentation", "create_studio_visual_need", "fit_scene_to_layout", "get_agent_runbook", "get_app_status", "get_cleanup_rule_profile", "get_deck_audit", "get_deck_contact_sheet", "get_deck_design_work_order", "get_deck_qualification", "get_deck_scene_summary", "get_design_contract", "get_design_thread", "get_pending_proposal_manifest", "get_qualification_contact_sheet", "get_qualification_slide", "get_resource_preview", "get_resource_text", "get_slide_design_context", "get_slide_design_work_order", "get_slide_inspection_packet", "get_slide_measurements", "get_slide_render", "get_slide_render_comparison", "get_slide_scene", "get_studio_composition_plan", "get_studio_concept_reference", "get_studio_deck_consistency", "get_studio_presentation_build_status", "get_studio_slide_critique", "get_studio_visual_need_brief", "get_studio_web_scene", "get_template_layout_catalog", "get_template_layout_render", "hold_studio_visual_need", "list_decks", "list_design_threads", "list_resources", "list_studio_visual_needs", "plan_studio_table_continuation", "preview_studio_fresh_composition", "publish_studio_component_style", "publish_studio_table_exemplar", "recommend_slide_layouts", "reconstruct_studio_concept", "record_deck_qualification_review", "record_proposal_visual_critique", "record_studio_visual_critique", "refine_studio_layout", "refine_studio_table", "reject_design_proposal", "remove_studio_concept_reference", "repair_studio_objective_issues", "run_deck_qualification", "set_deck_template_target", "solve_and_stage_alignment", "solve_and_stage_distribution", "solve_and_stage_group_layout", "solve_and_stage_safe_region", "solve_and_stage_table_layout", "solve_and_stage_text_fit", "stage_designer_cleanup", "stage_font_cleanup", "stage_slide_geometry_update", "stage_slide_layout_update", "stage_slide_native_layout", "stage_slide_recomposition", "stage_slide_visual_design", "stage_studio_web_design", "stage_table_design_update"]);
    const contractTool = result.tools.find((tool) => tool.name === "get_design_contract");
    assert.match(contractTool?.description ?? "", /improving every slide/i);
    const contract = await client.callTool({ name: "get_design_contract", arguments: {} });
    assert.equal(contract.isError, undefined);
    assert.equal((contract.structuredContent as { defaultMode?: { name?: string } })?.defaultMode?.name, "designer-cleanup");
    assert.match(JSON.stringify(contract.structuredContent), /independently rendered export/i);
    assert.match(JSON.stringify(contract.structuredContent), /design thread/i);
    assert.match(JSON.stringify(contract.structuredContent), /stable object, text range, table cell\/range, or normalized region/i);
    assert.match(JSON.stringify(contract.structuredContent), /measure every cell/i);
    assert.match(JSON.stringify(contract.structuredContent), /continuation slide/i);
    assert.match(JSON.stringify(contract.structuredContent), /reversible transaction history/i);
    assert.equal((contract.structuredContent as { defaults?: { slide?: { aspectRatio?: string }; typography?: { family?: string } } })?.defaults?.slide?.aspectRatio, "16:9");
    assert.equal((contract.structuredContent as { defaults?: { typography?: { family?: string } } })?.defaults?.typography?.family, "Aptos");
    assert.equal((contract.structuredContent as { tableProfile?: { cellPaddingPt?: { left?: number } } })?.tableProfile?.cellPaddingPt?.left, 6);
    assert.match(JSON.stringify(contract.structuredContent), /Do not redraw each slide as an unrelated one-off canvas/i);
    assert.match(JSON.stringify(contract.structuredContent), /constrained semantic HTML\/CSS Studio Web Scene/i);
    assert.match(JSON.stringify(contract.structuredContent), /one current presentation/i);
    assert.match(JSON.stringify(contract.structuredContent), /Changing only type size or font family/i);
    assert.match(JSON.stringify(contract.structuredContent), /concept.*provide art direction/i);
    assert.match(JSON.stringify(contract.structuredContent), /reconstruct_studio_concept.*typography-only/i);
    assert.match(JSON.stringify(contract.structuredContent), /create_studio_presentation/);
    assert.match(JSON.stringify(contract.structuredContent), /without requiring a starter PowerPoint/i);
    assert.match(JSON.stringify(contract.structuredContent), /source always wins/i);
    assert.match(JSON.stringify(contract.structuredContent), /rebuild-figure/i);
    const runbookTool = result.tools.find((tool) => tool.name === "get_agent_runbook");
    assert.match(runbookTool?.description ?? "", /recommended next MCP action/i);
    assert.match(runbookTool?.description ?? "", /preserve\/polish\/recompose\/rebuild-figure/i);
    assert.equal(runbookTool?.annotations?.readOnlyHint, true);
    const resourceTextTool = result.tools.find((tool) => tool.name === "get_resource_text");
    assert.match(resourceTextTool?.description ?? "", /single AI access switch/i);
    assert.equal(resourceTextTool?.annotations?.readOnlyHint, true);
    const createPresentationTool = result.tools.find((tool) => tool.name === "create_studio_presentation");
    assert.match(createPresentationTool?.description ?? "", /native Studio JSON\/HTML\/CSS scene/i);
    assert.match(createPresentationTool?.description ?? "", /first slide must use an approved ORNL title layout/i);
    assert.match(createPresentationTool?.description ?? "", /does not save.*export/i);
    assert.equal(createPresentationTool?.annotations?.destructiveHint, false);
    const conceptTool = result.tools.find((tool) => tool.name === "attach_studio_concept_reference");
    assert.match(conceptTool?.description ?? "", /Generated text, logos, data, claims, and technical details are always untrusted/i);
    assert.equal(conceptTool?.annotations?.destructiveHint, false);
    const reconstructConceptTool = result.tools.find((tool) => tool.name === "reconstruct_studio_concept");
    assert.match(reconstructConceptTool?.description ?? "", /material editable Studio composition/i);
    assert.match(reconstructConceptTool?.description ?? "", /rather than merely shrinking type/i);
    assert.equal(reconstructConceptTool?.annotations?.destructiveHint, false);
    const compositionPlanTool = result.tools.find((tool) => tool.name === "get_studio_composition_plan");
    assert.match(compositionPlanTool?.description ?? "", /communication job/i);
    assert.match(compositionPlanTool?.description ?? "", /exact approved native layout/i);
    assert.equal(compositionPlanTool?.annotations?.readOnlyHint, true);
    const stageStudioTool = result.tools.find((tool) => tool.name === "stage_studio_web_design");
    assert.match(stageStudioTool?.description ?? "", /omit recipe/i);
    assert.match(stageStudioTool?.description ?? "", /intermediate recipe canvas is not reviewable output/i);
    const conceptPreviewTool = result.tools.find((tool) => tool.name === "get_resource_preview");
    assert.match(conceptPreviewTool?.description ?? "", /single AI access switch/i);
    const visualNeedTool = result.tools.find((tool) => tool.name === "create_studio_visual_need");
    assert.match(visualNeedTool?.description ?? "", /default brief exposes abstract structure only/i);
    assert.match(visualNeedTool?.description ?? "", /does not call an image model/i);
    assert.equal(visualNeedTool?.annotations?.destructiveHint, false);
    const visualNeedBriefTool = result.tools.find((tool) => tool.name === "get_studio_visual_need_brief");
    assert.match(visualNeedBriefTool?.description ?? "", /default prompt never contains source wording or source pixels/i);
    const visualNeedListTool = result.tools.find((tool) => tool.name === "list_studio_visual_needs");
    assert.match(visualNeedListTool?.description ?? "", /no slide text, source pixels, concept pixels, prompts, or presentation bytes/i);
    const centralBuildTool = result.tools.find((tool) => tool.name === "build_studio_presentation");
    assert.match(centralBuildTool?.description ?? "", /one persisted Studio Web Scene/i);
    assert.match(centralBuildTool?.description ?? "", /background build/i);
    assert.match(centralBuildTool?.description ?? "", /poll get_studio_presentation_build_status/i);
    assert.match(centralBuildTool?.description ?? "", /does not save or export/i);
    const centralBuildStatusTool = result.tools.find((tool) => tool.name === "get_studio_presentation_build_status");
    assert.match(centralBuildStatusTool?.description ?? "", /without blocking the app/i);
    assert.equal(centralBuildStatusTool?.annotations?.readOnlyHint, true);
    const cancelCentralBuildTool = result.tools.find((tool) => tool.name === "cancel_studio_presentation_build");
    assert.match(cancelCentralBuildTool?.description ?? "", /prior verified result remain intact/i);
    const qualificationTool = result.tools.find((tool) => tool.name === "run_deck_qualification");
    assert.match(qualificationTool?.description ?? "", /every slide.*private 2,200-pixel PNG/i);
    assert.match(qualificationTool?.description ?? "", /does not.*prove that the design is better/i);
    assert.equal(qualificationTool?.annotations?.destructiveHint, false);
    const qualificationLedgerTool = result.tools.find((tool) => tool.name === "get_deck_qualification");
    assert.match(qualificationLedgerTool?.description ?? "", /metadata alone cannot establish visual quality/i);
    assert.equal(qualificationLedgerTool?.annotations?.readOnlyHint, true);
    const qualificationSlideTool = result.tools.find((tool) => tool.name === "get_qualification_slide");
    assert.match(qualificationSlideTool?.description ?? "", /full-resolution Microsoft PowerPoint-native PNG/i);
    assert.match(qualificationSlideTool?.description ?? "", /issue crop/i);
    assert.equal(qualificationSlideTool?.annotations?.readOnlyHint, true);
    const qualificationSheetTool = result.tools.find((tool) => tool.name === "get_qualification_contact_sheet");
    assert.match(qualificationSheetTool?.description ?? "", /up to 40 authoritative PowerPoint-native/i);
    assert.equal(qualificationSheetTool?.annotations?.readOnlyHint, true);
    const qualificationReviewTool = result.tools.find((tool) => tool.name === "record_deck_qualification_review");
    assert.match(qualificationReviewTool?.description ?? "", /bound to both raster hashes/i);
    assert.match(qualificationReviewTool?.description ?? "", /does not change slide design/i);
    assert.match(qualificationReviewTool?.description ?? "", /source wins/i);
    assert.equal(qualificationReviewTool?.annotations?.destructiveHint, false);
    const refineStudioTool = result.tools.find((tool) => tool.name === "refine_studio_layout");
    assert.match(refineStudioTool?.description ?? "", /PowerPoint-native rendered text bounds/i);
    assert.match(refineStudioTool?.description ?? "", /relationship-preserving groups/i);
    assert.equal(refineStudioTool?.annotations?.destructiveHint, false);
    const refineTableTool = result.tools.find((tool) => tool.name === "refine_studio_table");
    assert.match(refineTableTool?.description ?? "", /stable node and cell IDs/i);
    assert.match(refineTableTool?.description ?? "", /merged spans.*semantic color role/i);
    assert.equal(refineTableTool?.annotations?.destructiveHint, false);
    const tableExemplarTool = result.tools.find((tool) => tool.name === "publish_studio_table_exemplar");
    assert.match(tableExemplarTool?.description ?? "", /same column count, header-row count, header merge pattern, and body merge pattern/i);
    assert.match(tableExemplarTool?.description ?? "", /never copies cell content/i);
    assert.match(tableExemplarTool?.description ?? "", /semantic colors/i);
    assert.equal(tableExemplarTool?.annotations?.destructiveHint, false);
    const tableContinuationTool = result.tools.find((tool) => tool.name === "plan_studio_table_continuation");
    assert.match(tableContinuationTool?.description ?? "", /do not split a merged cell/i);
    assert.match(tableContinuationTool?.description ?? "", /automatically materialized as editable output slides/i);
    assert.equal(tableContinuationTool?.annotations?.destructiveHint, false);
    const connectorTool = result.tools.find((tool) => tool.name === "author_studio_connector");
    assert.match(connectorTool?.description ?? "", /verified editable-diagram/i);
    assert.match(connectorTool?.description ?? "", /rejects guessed topology/i);
    assert.equal(connectorTool?.annotations?.destructiveHint, false);
    const consistencyTool = result.tools.find((tool) => tool.name === "get_studio_deck_consistency");
    assert.match(consistencyTool?.description ?? "", /title-grid outliers/i);
    assert.match(consistencyTool?.description ?? "", /related table structural styles/i);
    assert.equal(consistencyTool?.annotations?.readOnlyHint, true);
    const componentTool = result.tools.find((tool) => tool.name === "publish_studio_component_style");
    assert.match(componentTool?.description ?? "", /same semantic role and light\/dark surface class/i);
    assert.match(componentTool?.description ?? "", /exact wording, data, geometry/i);
    assert.match(componentTool?.description ?? "", /protected ORNL template slides/i);
    assert.equal(componentTool?.annotations?.destructiveHint, false);
    const studioCritiqueTool = result.tools.find((tool) => tool.name === "get_studio_slide_critique");
    assert.match(studioCritiqueTool?.description ?? "", /original PowerPoint slide/i);
    assert.match(studioCritiqueTool?.description ?? "", /Found issues/i);
    const recordStudioCritiqueTool = result.tools.find((tool) => tool.name === "record_studio_visual_critique");
    assert.match(recordStudioCritiqueTool?.description ?? "", /capped at three/i);
    const statusTool = result.tools.find((tool) => tool.name === "get_app_status");
    assert.match(statusTool?.description ?? "", /locked Mac/i);
    const stageTool = result.tools.find((tool) => tool.name === "stage_font_cleanup");
    assert.equal(stageTool?.annotations?.destructiveHint, false);
    assert.equal(stageTool?.annotations?.readOnlyHint, false);
    const designerTool = result.tools.find((tool) => tool.name === "stage_designer_cleanup");
    assert.match(designerTool?.description ?? "", /every slide/i);
    assert.match(designerTool?.description ?? "", /semantic colors/i);
    assert.match(designerTool?.description ?? "", /text-box alignment/i);
    assert.equal(designerTool?.annotations?.destructiveHint, false);
    const geometryTool = result.tools.find((tool) => tool.name === "stage_slide_geometry_update");
    assert.match(geometryTool?.description ?? "", /stable editable object/i);
    assert.match(geometryTool?.description ?? "", /Current\/Proposal/i);
    assert.equal(geometryTool?.annotations?.destructiveHint, false);
    const layoutTool = result.tools.find((tool) => tool.name === "stage_slide_layout_update");
    assert.match(layoutTool?.description ?? "", /one atomic design transaction/i);
    assert.match(layoutTool?.description ?? "", /worsened text fit/i);
    assert.match(layoutTool?.description ?? "", /newly increased overlap/i);
    assert.equal(layoutTool?.annotations?.destructiveHint, false);
    const visualDesignTool = result.tools.find((tool) => tool.name === "stage_slide_visual_design");
    assert.match(visualDesignTool?.description ?? "", /editable PowerPoint-native text hierarchy/i);
    assert.match(visualDesignTool?.description ?? "", /cannot add or rewrite claims/i);
    assert.match(visualDesignTool?.description ?? "", /accumulate/i);
    assert.equal(visualDesignTool?.annotations?.destructiveHint, false);
    const tableDesignTool = result.tools.find((tool) => tool.name === "stage_table_design_update");
    assert.match(tableDesignTool?.description ?? "", /dense-technical/i);
    assert.match(tableDesignTool?.description ?? "", /shared/i);
    assert.match(tableDesignTool?.description ?? "", /unrelated comments remain active/i);
    assert.match(JSON.stringify(tableDesignTool?.inputSchema), /addressedThreadIds/);
    assert.match(JSON.stringify(tableDesignTool?.inputSchema), /designStandardVersion/);
    assert.match(JSON.stringify(tableDesignTool?.inputSchema), /semanticColorPolicy/);
    assert.match(tableDesignTool?.description ?? "", /role-to-cell mapping/i);
    const tableLayoutTool = result.tools.find((tool) => tool.name === "solve_and_stage_table_layout");
    assert.match(tableLayoutTool?.description ?? "", /preserves a table that already passes/i);
    assert.match(tableLayoutTool?.description ?? "", /minimum amount that fits inside the safe region/i);
    const distributionTool = result.tools.find((tool) => tool.name === "solve_and_stage_distribution");
    assert.match(distributionTool?.description ?? "", /object groups/i);
    assert.match(JSON.stringify(distributionTool?.inputSchema), /groups/);
    const safeRegionTool = result.tools.find((tool) => tool.name === "solve_and_stage_safe_region");
    assert.match(safeRegionTool?.description ?? "", /minimum distance/i);
    assert.equal(safeRegionTool?.annotations?.destructiveHint, false);
    const groupLayoutTool = result.tools.find((tool) => tool.name === "solve_and_stage_group_layout");
    assert.match(groupLayoutTool?.description ?? "", /semantic slot/i);
    assert.match(groupLayoutTool?.description ?? "", /internal geometry/i);
    assert.match(groupLayoutTool?.description ?? "", /hierarchy-aware spacing/i);
    assert.match(JSON.stringify(groupLayoutTool?.inputSchema), /preferredGapPt/);
    assert.match(JSON.stringify(groupLayoutTool?.inputSchema), /groupRoles/);
    assert.match(JSON.stringify(groupLayoutTool?.inputSchema), /allowResponsiveScale/);
    const sceneLayoutTool = result.tools.find((tool) => tool.name === "fit_scene_to_layout");
    assert.match(sceneLayoutTool?.description ?? "", /responsive semantic regions/i);
    assert.match(sceneLayoutTool?.description ?? "", /cross-region collisions/i);
    assert.match(JSON.stringify(sceneLayoutTool?.inputSchema), /slotId/);
    assert.match(JSON.stringify(sceneLayoutTool?.inputSchema), /groupRoles/);
    assert.match(JSON.stringify(sceneLayoutTool?.inputSchema), /minimumScale/);
    const textFitTool = result.tools.find((tool) => tool.name === "solve_and_stage_text_fit");
    assert.match(textFitTool?.description ?? "", /PowerPoint-native rendered bounds/i);
    assert.match(textFitTool?.description ?? "", /never silently shrinks text/i);
    assert.match(JSON.stringify(textFitTool?.inputSchema), /addressedThreadIds/);
    const critiqueTool = result.tools.find((tool) => tool.name === "record_proposal_visual_critique");
    assert.match(critiqueTool?.description ?? "", /capped at three attempts/i);
    assert.match(critiqueTool?.description ?? "", /withheld/i);
    assert.match(JSON.stringify(critiqueTool?.inputSchema), /inspectionRevision/);
    assert.match(JSON.stringify(critiqueTool?.inputSchema), /intentReview/);
    const proposalManifestTool = result.tools.find((tool) => tool.name === "get_pending_proposal_manifest");
    assert.match(proposalManifestTool?.description ?? "", /selected command kinds/i);
    assert.match(proposalManifestTool?.description ?? "", /without returning slide text or presentation bytes/i);
    assert.equal(proposalManifestTool?.annotations?.readOnlyHint, true);
    const renderTool = result.tools.find((tool) => tool.name === "get_slide_render");
    assert.match(renderTool?.description ?? "", /Microsoft PowerPoint render/i);
    assert.match(renderTool?.description ?? "", /renderer provenance/i);
    assert.match(JSON.stringify(renderTool?.inputSchema), /source/);
    assert.match(JSON.stringify(renderTool?.inputSchema), /export/);
    const catalogTool = result.tools.find((tool) => tool.name === "get_template_layout_catalog");
    assert.match(catalogTool?.description ?? "", /preferred\/minimum\/maximum bounds/i);
    assert.match(catalogTool?.description ?? "", /alignment and padding intent/i);
    assert.match(catalogTool?.description ?? "", /semantic intent/i);
    assert.match(catalogTool?.description ?? "", /no template bytes/i);
    assert.equal(catalogTool?.annotations?.readOnlyHint, true);
    const layoutRenderTool = result.tools.find((tool) => tool.name === "get_template_layout_render");
    assert.match(layoutRenderTool?.description ?? "", /authoritative Microsoft PowerPoint render/i);
    assert.match(layoutRenderTool?.description ?? "", /slot geometry/i);
    assert.equal(layoutRenderTool?.annotations?.readOnlyHint, true);
    const recommendationTool = result.tools.find((tool) => tool.name === "recommend_slide_layouts");
    assert.match(recommendationTool?.description ?? "", /deterministically rank/i);
    assert.match(recommendationTool?.description ?? "", /PowerPoint-native renders/i);
    assert.equal(recommendationTool?.annotations?.readOnlyHint, true);
    const sceneSummaryTool = result.tools.find((tool) => tool.name === "get_deck_scene_summary");
    assert.match(sceneSummaryTool?.description ?? "", /editable-native/i);
    assert.match(sceneSummaryTool?.description ?? "", /package bytes/i);
    assert.equal(sceneSummaryTool?.annotations?.readOnlyHint, true);
    const slideSceneTool = result.tools.find((tool) => tool.name === "get_slide_scene");
    assert.match(slideSceneTool?.description ?? "", /source-bound object/i);
    assert.match(slideSceneTool?.description ?? "", /z-order/i);
    assert.match(slideSceneTool?.description ?? "", /authoritative Current render/i);
    assert.equal(slideSceneTool?.annotations?.readOnlyHint, true);
    const studioSceneTool = result.tools.find((tool) => tool.name === "get_studio_web_scene");
    assert.match(studioSceneTool?.description ?? "", /canonical semantic HTML\/CSS scene/i);
    assert.match(studioSceneTool?.description ?? "", /actual composition decision/i);
    assert.equal(studioSceneTool?.annotations?.readOnlyHint, true);
    const studioStageTool = result.tools.find((tool) => tool.name === "stage_studio_web_design");
    assert.match(studioStageTool?.description ?? "", /fresh-composition/i);
    assert.match(studioStageTool?.description ?? "", /same scene, not alternate proposals/i);
    assert.match(studioStageTool?.description ?? "", /PowerPoint-native visual QA/i);
    assert.match(studioStageTool?.description ?? "", /substantive layout decision/i);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-two-column/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-card-grid/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-objective-columns/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-steps-evidence/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-labeled-figure-grid/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-image-series/);
    assert.match(studioStageTool?.description ?? "", /never flatten the groups into stacked text and tiny thumbnails/i);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /ornl-title-question-diagram/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /fresh-composition/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /nodeFrames/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /nodeStyles/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /figureTreatments/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /visualNeedIds/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /preserve-and-frame/);
    assert.match(JSON.stringify(studioStageTool?.inputSchema), /redraw-candidate/);
    assert.equal(studioStageTool?.annotations?.destructiveHint, false);
    const inspectionTool = result.tools.find((tool) => tool.name === "get_slide_inspection_packet");
    assert.match(inspectionTool?.description ?? "", /Found issues/i);
    assert.match(inspectionTool?.description ?? "", /Rechecking original intent/i);
    const freshCompositionTool = result.tools.find((tool) => tool.name === "preview_studio_fresh_composition");
    assert.match(freshCompositionTool?.description ?? "", /genuinely new editable native PowerPoint output slides/i);
    assert.match(freshCompositionTool?.description ?? "", /exact source\/output text/i);
    assert.match(freshCompositionTool?.description ?? "", /does not preserve the imported master/i);
    assert.match(freshCompositionTool?.description ?? "", /never applies, saves, exports, or overwrites/i);
    assert.equal(freshCompositionTool?.annotations?.destructiveHint, false);
    assert.equal(freshCompositionTool?.annotations?.readOnlyHint, false);
    const workOrderTool = result.tools.find((tool) => tool.name === "get_slide_design_work_order");
    assert.match(workOrderTool?.description ?? "", /exact locked copy/i);
    assert.match(workOrderTool?.description ?? "", /iterative visual-design loop/i);
    assert.equal(workOrderTool?.annotations?.readOnlyHint, true);
    const deckWorkOrderTool = result.tools.find((tool) => tool.name === "get_deck_design_work_order");
    assert.match(deckWorkOrderTool?.description ?? "", /one for each communication archetype present/i);
    assert.match(deckWorkOrderTool?.description ?? "", /before propagating any layout pattern/i);
    const contactSheetTool = result.tools.find((tool) => tool.name === "get_deck_contact_sheet");
    assert.match(contactSheetTool?.description ?? "", /up to 40 PowerPoint-native slide thumbnails/i);
    assert.match(contactSheetTool?.description ?? "", /not point geometry/i);
    assert.equal(contactSheetTool?.annotations?.readOnlyHint, true);
    const comparisonTool = result.tools.find((tool) => tool.name === "get_slide_render_comparison");
    assert.match(comparisonTool?.description ?? "", /side-by-side Microsoft PowerPoint image/i);
    assert.match(comparisonTool?.description ?? "", /does not prove the proposal is better/i);
    const rejectTool = result.tools.find((tool) => tool.name === "reject_design_proposal");
    assert.match(rejectTool?.description ?? "", /visual-regression rationale/i);
    assert.match(rejectTool?.description ?? "", /never apply or export/i);
    assert.equal(rejectTool?.annotations?.destructiveHint, false);
    const recomposeTool = result.tools.find((tool) => tool.name === "stage_slide_recomposition");
    assert.match(recomposeTool?.description ?? "", /semantic slots/i);
    assert.match(recomposeTool?.description ?? "", /Atomically apply one real approved Template Pack layout/i);
    assert.match(recomposeTool?.description ?? "", /reuses an exact SHA-256-matching native layout/i);
    assert.equal(recomposeTool?.annotations?.destructiveHint, false);
    const nativeLayoutTool = result.tools.find((tool) => tool.name === "stage_slide_native_layout");
    assert.match(nativeLayoutTool?.description ?? "", /reuses an exact SHA-256-matching native layout/i);
    assert.match(nativeLayoutTool?.description ?? "", /master\/layout\/theme\/media dependency graph/i);
    assert.match(nativeLayoutTool?.description ?? "", /placeholder identities/i);
    assert.match(nativeLayoutTool?.description ?? "", /repoints only the named slide/i);
    assert.match(nativeLayoutTool?.description ?? "", /reflow scope/i);
    assert.equal(nativeLayoutTool?.annotations?.destructiveHint, false);
  } finally {
    await client.close();
  }
});
